### ISSUE TITLE
Installation stardog free

### ISSUE THREAD

**Issue by oschihin** [Staatsarchiv-Basel-Stadt/RDF-Pipeline#12]
* [x] Lizenzbezug @oschihin 
* [x] Installation (als Container)
* [x] Konfiguration virtual graph (ODBC, scope-DB) #18 
* [x] Security klären (https, etc.)
* [x] Abnahme

**Comment by oschihin** [comment]
@ludovicm67 : move stardock-stack repo from internal to here: https://github.com/Staatsarchiv-Basel-Stadt/stardog-docker

**Comment by ludovicm67** [comment]
Yes, it's done! I also configured GitHub Actions to build the custom Docker image to add Oracle JDBC driver support.

**Comment by oschihin** [comment]
Thanks. Still, I guess we use the internal custom repo für builds. See [Issue 14](#14) and [this comment](https://github.com/Staatsarchiv-Basel-Stadt/RDF-Pipeline/issues/14#issuecomment-946665748)

**Comment by ludovicm67** [comment]
My understanding is that it should be only for https://github.com/Staatsarchiv-Basel-Stadt/RDF-Pipeline, no?

**Comment by ktk** [comment]
@oschihin let's document here where (in which directory) we keep the persistence (volumes of docker).

**Comment by oschihin** [comment]
@ktk 
* stardog_home with licence key and persistent data: `~ /volumes/stardog-home`
* docker repo with compose file etc: `~/services/stardog-docker`
* notes, documentation, the like: `~/doku`

can be removed: `~/stardog-home`
