### ISSUE TITLE
Verbindung github / internes docker-Repo

### ISSUE THREAD

**Issue by oschihin** [Staatsarchiv-Basel-Stadt/RDF-Pipeline#14]
Ziel: Gitlab Pipeline läuft im zazuko.tools Gitlab server

* [x] Zugänge zum internen Repo für @oschihin klären
* [x] ~~Code in [diesem github-Repo](..) wird regelmässig ins interne docker-Repo von zazuko übernommen~~
* [x] GitLab is the source of truth, **no** commits will ever go into this repo, Gitlab will push at the end of a CI/CD cycle to this repo to make sure the source is public & up-to-date

**Comment by ktk** [comment]
- [ ] Check if we can build on GitHub in a non-paying scenario
- [ ] If not, move build to Zazuko Customer Gitlab
- [ ] Create user for Oliver

**Comment by ludovicm67** [comment]
Builds for https://github.com/Staatsarchiv-Basel-Stadt/RDF-Pipeline are now happening on https://gitlab.zazuko.tools/stabs/staatsarchiv-ld-pipeline as requested.

**Comment by ludovicm67** [comment]
To be able to configure GitLab to push to this GitHub repo, I will need to be able to configure deploy keys (https://docs.github.com/en/developers/overview/managing-deploy-keys#deploy-keys).

Is it possible that @oschihin grants me admin for this repo?

**Comment by oschihin** [comment]
@ludovicm67 tu as Role:Admin, use responsibly ;-)

**Comment by ludovicm67** [comment]
I configured the GitLab repo to push changes to this repo using a Deploy Key.

**Comment by oschihin** [comment]
@ludovicm67 thanks
I downgraded everybody to Role: Read, so that no commits are possible. I'll do a test today and will then close the issue.

**Comment by oschihin** [comment]
@ludovicm67 works
