### ISSUE TITLE
Running container auf altem Server (Replace scope virtual.properties)

### ISSUE THREAD

**Issue by ktk** [Staatsarchiv-Basel-Stadt/RDF-Pipeline#16]

**Comment by ktk** [comment]
Kann ich nach etwas bestimmtem suchen? Der generierte Dump hat im Moment 8503836 triples.

**Comment by oschihin** [comment]
:+1: 
schaut gut aus. Einfach: Aktuelles Set hat `https`, z.B. https://ld.staatsarchiv.bs.ch/Record/138430

**Comment by oschihin** [comment]
@ktk 
nach gestern schaut es nun gut aus, die Zahlen stimmen. Im Endpoint ist dieselbe Anzahl Triples wie im Dump (8505883).
https://s.zazuko.com/nFVun
Intern sind es 62 3Triples weniger, das sind die Metadaten aus der Pipeline.
Bin gespannt, können das Ticket am Donnerstag wahrsch. schliessen

**Comment by oschihin** [comment]
@ktk 
Updates von gestern liefen durch, Zahlen stimmen. Ist also mindestens zweimal gelaufen. Schliesse hier, danke
