### ISSUE TITLE
Http error 401 on materialize

### ISSUE THREAD

**Issue by oschihin** [Staatsarchiv-Basel-Stadt/RDF-Pipeline#5]
When called through cron, materialize generates an error (http status 401 by stardog server, see below). When I call the same command (`/usr/src/app/cron/cron-materialize.sh > /proc/1/fd/1 2>/proc/1/fd/2`) on the bash inside the container, it works just fine.

@ktk : any idea? Is this maybe connected to #1 ?

```
Starting pull...
No change in repository
pull done.

> staatsarchiv-ld@0.0.0 materialize /usr/src/app
> node shell/materialize.js

Could not execute request, got 401: Unauthorized
Could not execute request, got 401: Unauthorized

> staatsarchiv-ld@0.0.0 mappingUpdate /usr/src/app
> node shell/mappingUpdate.js

Starting pull...
No change in repository
pull done.
```

**Comment by oschihin** [comment]
@ktk 
Problem mit env on cron, now solved by (d197a8f9c2c7a5c94aaf7abbeef3c04f0a3c8e7a)

```
> staatsarchiv-ld@0.0.0 materialize /usr/src/app
> node shell/materialize.js

Request successfully executed, got 200: OK
Request successfully executed, got 200: OK

**Comment by oschihin** [comment]
[stardog@pvpdstat01 ~]$ docker exec -it osrdfpipe bash
root@f166b6d5c460:/opt/StABS-scope2RDF# /usr/src/app/cron/cron-materialize.sh

> staatsarchiv-ld@0.0.0 materialize /usr/src/app
> node shell/materialize.js

Could not execute request, got 401: Unauthorized
Could not execute request, got 401: Unauthorized

**Comment by ktk** [comment]
Ist die Stardog-Lizenz ausgelaufen?

**Comment by oschihin** [comment]
> Ist die Stardog-Lizenz ausgelaufen?

Nein, die läuft in 18 Tagen ab.

**Comment by oschihin** [comment]
env variables gehen verloren bei `docker restart`!?

Wenn ich `export stardog_user=***` und `export stardog_password=***` im Container setze, funktioniert es wieder? Strange!

**Comment by ktk** [comment]
Closing for the moment. If it re-appears we will open a new issue.
